"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 18:41:02.353576
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aws_account_id', sa.String(length=12), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('role_arn', sa.String(length=256), nullable=True),
    sa.Column('stack_id', sa.String(length=256), nullable=True),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_aws_account_id'), 'accounts', ['aws_account_id'], unique=True)
    op.create_table('benchmark_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('smape', sa.Float(), nullable=False),
    sa.Column('mase', sa.Float(), nullable=False),
    sa.Column('p90_coverage_pct', sa.Float(), nullable=False),
    sa.Column('inference_latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_usd', sa.Float(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=64), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'horizon')
    )
    op.create_table('policy_summary',
    sa.Column('policy', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sla_violation_minutes', sa.Integer(), nullable=False),
    sa.Column('overload_events', sa.Integer(), nullable=False),
    sa.Column('underutilization_events', sa.Integer(), nullable=False),
    sa.Column('scaling_oscillations', sa.Integer(), nullable=False),
    sa.Column('infrastructure_cost_usd', sa.Float(), nullable=False),
    sa.Column('model_inference_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('avg_utilization_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('policy')
    )
    op.create_table('sim_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.Integer(), nullable=False),
    sa.Column('now', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tick_ms', sa.Float(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_recommendation_id', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sns_message_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_alerts_dedupe_key'), 'alerts', ['dedupe_key'], unique=False)
    op.create_table('capacity_recommendations',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('forecast_p90', sa.Float(), nullable=False),
    sa.Column('throughput_per_unit', sa.Float(), nullable=False),
    sa.Column('safety_margin_pct', sa.Float(), nullable=False),
    sa.Column('raw_required_units', sa.Integer(), nullable=False),
    sa.Column('required_units', sa.Integer(), nullable=False),
    sa.Column('current_units', sa.Integer(), nullable=False),
    sa.Column('min_units', sa.Integer(), nullable=False),
    sa.Column('max_units', sa.Integer(), nullable=False),
    sa.Column('hysteresis_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_remaining_sec', sa.Integer(), nullable=False),
    sa.Column('budget_threshold_usd', sa.Float(), nullable=False),
    sa.Column('budget_capped', sa.Boolean(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('decision_state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_recommendations_account_id'), 'capacity_recommendations', ['account_id'], unique=False)
    op.create_table('confidence_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('target_coverage_pct', sa.Float(), nullable=False),
    sa.Column('actual_coverage_pct', sa.Float(), nullable=False),
    sa.Column('calibration_error_pct', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fallback_model', sa.String(length=32), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'model', 'horizon')
    )
    op.create_index(op.f('ix_confidence_snapshots_account_id'), 'confidence_snapshots', ['account_id'], unique=False)
    op.create_table('cost_sla_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('instance_hours', sa.Float(), nullable=False),
    sa.Column('task_hours', sa.Float(), nullable=False),
    sa.Column('model_inference_cost_usd', sa.Float(), nullable=False),
    sa.Column('infrastructure_cost_usd', sa.Float(), nullable=False),
    sa.Column('sla_violation_minutes', sa.Integer(), nullable=False),
    sa.Column('overload_events', sa.Integer(), nullable=False),
    sa.Column('underutilization_events', sa.Integer(), nullable=False),
    sa.Column('scaling_oscillations', sa.Integer(), nullable=False),
    sa.Column('cost_by_resource', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'day', 'region')
    )
    op.create_index(op.f('ix_cost_sla_metrics_account_id'), 'cost_sla_metrics', ['account_id'], unique=False)
    op.create_table('fleet_state',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('current_units', sa.Integer(), nullable=False),
    sa.Column('controller', sa.JSON(), nullable=False),
    sa.Column('suppress_until_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'region', 'resource_type')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('origin_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead', sa.Integer(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'region', 'model', 'origin_ts', 'lead')
    )
    op.create_index('ix_forecasts_target', 'forecasts', ['account_id', 'region', 'model', 'lead', 'target_ts'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewers_k', sa.Float(), nullable=False),
    sa.Column('requests_per_s', sa.Float(), nullable=False),
    sa.Column('cpu_util', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('bytes_out_gb', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'region', 'ts')
    )
    op.create_index('ix_metrics_acct_region_ts', 'metrics', ['account_id', 'region', 'ts'], unique=False)
    op.create_table('scaling_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_units', sa.Integer(), nullable=False),
    sa.Column('to_units', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('forecast_p90', sa.Float(), nullable=False),
    sa.Column('aws_desired_count', sa.Integer(), nullable=True),
    sa.Column('aws_request', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scaling_decisions_account_id'), 'scaling_decisions', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scaling_decisions_account_id'), table_name='scaling_decisions')
    op.drop_table('scaling_decisions')
    op.drop_index('ix_metrics_acct_region_ts', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_forecasts_target', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('fleet_state')
    op.drop_index(op.f('ix_cost_sla_metrics_account_id'), table_name='cost_sla_metrics')
    op.drop_table('cost_sla_metrics')
    op.drop_index(op.f('ix_confidence_snapshots_account_id'), table_name='confidence_snapshots')
    op.drop_table('confidence_snapshots')
    op.drop_index(op.f('ix_capacity_recommendations_account_id'), table_name='capacity_recommendations')
    op.drop_table('capacity_recommendations')
    op.drop_index(op.f('ix_alerts_dedupe_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sim_state')
    op.drop_table('policy_summary')
    op.drop_table('benchmark_results')
    op.drop_index(op.f('ix_accounts_aws_account_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
